### ISSUE TITLE
Missing `request` peer dependency

### ISSUE THREAD

**Issue by rtritto** [postor/free-http-proxy#4]
`request` is a peer dependency of `request-promise`, so must include it as peer dependency (transitive peer dependencies).

## Changes
`package.json`
```diff
"peerDependencies": {
+  "request": "*",
  ...
}
```

**Comment by postor** [comment]
can you make a pull request so I can merge?

**Comment by rtritto** [comment]
I noticed that `request` and `request-promise` are deprecated ([source](https://github.com/request/request/issues/3142)).

I recommend to replace `requst-promise` with `axios`.

**Comment by rtritto** [comment]
So should we close this issue and open another for the replace with axios?
Or I can do directly the PR.

**Comment by postor** [comment]
sure
